version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geotrack-db-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: client_tracking_app
    ports:
      - "5432:5432"
    volumes:
      - geotrack_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  geotrack_data:
