services:
  - type: web
    name: geotrack-backend
    env: node
    plan: free
    buildCommand: "npm install"
    # Run migrations and seeding before starting the server
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: postgresql://geotrack_dbtest_user:DpQrv5nopeTKqIUNQB6pQYeCdJgIlOxA@dpg-d7grg6po3t8c7392p2tg-a.oregon-postgres.render.com:5432/geotrack_dbtest
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: LICENSE_WEBHOOK_SECRET
        sync: false
      - key: MIDDLEWARE_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
